import json
import numpy as np

try:
    import Part
    import Mesh
    import Draft
    import Arch
    import BOPTools

    import importOBJ
except ImportError as e:
    print('FreeCAD is not available, running standalone.')
    print(e)



if __name__ == '__main__':

    try:
        App = FreeCAD
    except NameError as e:
        print('FreeCAD is not available, running standalone.')
        print(e)

    path_local = '/Users/fnoic/PycharmProjects/reconstruct/'
    path_config = 'config_reconstruct_a.json'
    # load yaml file content
    config = json.load(open(path_local + path_config, 'r'))

    with open(path_local + config['path_skeleton'], 'rb') as f:
        skeleton_dict = json.load(f)
        # print(skeleton_dict)
        # skeleton = pickle.load(f)
        # print(skeleton.bones)

    try:
        App.newDocument(config['export_filename'])
        # fcdocexport = App.getDocument(config['export_filename'])
        # fcdocexport.addObject('PartDesign::Body', 'Body')
        fcdoc = App.getDocument(config['export_filename'])
        body = fcdoc.addObject('PartDesign::Body', 'Body')
    except Exception as e:
        print('FreeCAD is not available, running standalone.')
        print(e)

    for bone_flag in skeleton_dict.keys():
        bone_id = int(bone_flag.split('_')[1])
        bone = skeleton_dict[bone_flag]
        # cs vertices
        beam_verts = np.asarray(bone['beam_verts'])
        # center vertices around origin = bone.line_cog_...
        delta_x = beam_verts[0, 0] + (np.max(beam_verts[:, 0] - np.min(beam_verts[:, 0])) / 2)
        delta_y = beam_verts[0, 1] + (np.max(beam_verts[:, 1] - np.min(beam_verts[:, 1])) / 2)
        # beam_verts[:, 0] -= delta_x
        # beam_verts[:, 1] -= delta_y
        beam_verts = np.hstack((beam_verts, np.zeros((beam_verts.shape[0], 1))))
        # rotation matrix
        rot_mat = np.asarray(bone['rot_mat'])
        rot_mat = rot_mat.T


        # create placement
        try:
            pl = FreeCAD.Placement()
            pl.Base = FreeCAD.Vector(bone['start'][0], bone['start'][1], bone['start'][2])
            pl.Rotation = FreeCAD.Rotation(rot_mat[0][0], rot_mat[0][1], rot_mat[0][2],
                                           rot_mat[1][0], rot_mat[1][1], rot_mat[1][2],
                                           rot_mat[2][0], rot_mat[2][1], rot_mat[2][2])
            fcdoc.recompute()

            # create bone line
            vector = np.asarray([bone['end'][i] - bone['start'][i] for i in range(3)])
            length = np.linalg.norm(vector)
            points = [FreeCAD.Vector(bone['start'][0], bone['start'][1], bone['start'][2]),
                      FreeCAD.Vector(bone['end'][0], bone['end'][1], bone['end'][2])]
            line = Draft.make_wire(points, placement=pl, closed=False, face=True, support=None)
            Draft.autogroup(line)
            fcdoc.recompute()


            # pl.Rotation.Matrix = rot_mat

            # create offset on yz plane with x coordinate of midpoint + rotated plane
            point = FreeCAD.ActiveDocument.addObject("Part::Vertex", f"Point{bone_id}")
            point.X = bone['start'][0]
            point.Y = bone['start'][1]
            point.Z = bone['start'][2]

            # create plane
            # datumplane = fcdoc.getObject('Body').newObject('PartDesign::Plane', f'DatumPlane{bone_id}')
            # datumplane.AttachmentOffset = App.Placement(App.Vector(0.0000000000, 0.0000000000, 0.0000000000), App.Rotation(0.0000000000, 0.0000000000, 0.0000000000))
            # datumplane.MapReversed = False

            # datumplane.Support = [(point, f"Point{bone_id}")]
            # datumplane.MapPathParameter = 0.000000
            # datumplane.MapMode = 'Translate'
            # datumplane.Placement.Rotation.Matrix = rot_mat
            # datumplane.recompute()
            #
            # create cross-section
            fcdoc.getObject('Body').newObject('Sketcher::SketchObject', f'cross_section{bone_id}')
            polygon = fcdoc.getObject(f'cross_section{bone_id}')
            # polygon.Support = (fcdoc.getObject(f'DatumPlane{bone_id}'), [''])
            polygon.MapMode = 'FlatFace'
            polygon_edges = []
            for i in range(len(beam_verts)):
                if i != len(beam_verts) - 1:
                    polygon_edges.append((i, i + 1))
                else:
                    polygon_edges.append((i, 0))

            for edge in polygon_edges:
                polygon.addGeometry(Part.LineSegment(
                    App.Vector(beam_verts[edge[0]][0], beam_verts[edge[0]][1], beam_verts[edge[0]][2]),
                    App.Vector(beam_verts[edge[1]][0], beam_verts[edge[1]][1], beam_verts[edge[1]][2])),
                    False
                )
            polygon.Placement = pl
            Draft.autogroup(polygon)
            fcdoc.recompute()
            #
            # execute sweep operation
            fcdoc.addObject('Part::Sweep', f'beam{bone_id}')
            sweep = fcdoc.getObject(f'beam{bone_id}')
            sweep.Sections = polygon
            sweep.Spine = line
            sweep.Solid = True
            sweep.Frenet = False
            fcdoc.recompute()

            # beam = Arch.makeStructure(polygon, height=length)
            # beam.Profile = "Crosssection"
            # beam.Placement.Base.x += vector[0]
            # beam.Placement.Base.y += vector[1]
            # beam.Placement.Base.z += vector[2]
            #
            # beam.IfcType = 'Beam'
            # Draft.autogroup(beam)
            # fcdoc.recompute()
            # fcdoc.recompute()
            #
            # fcdoc.removeObject(f'DatumPlane{bone_id}')
            # fcdoc.removeObject(f'DatumPlane{bone_id}')
            # fcdoc.recompute()






        except Exception as e:
            print('FreeCAD is not available, running standalone.')
            print(e)

        # rotation matrix


        # break


    raise Exception('hello silly my old friend')
